language: php
sudo: false
php:
  - 7.4
  - 8.0

before_script:
  - composer self-update -q
  - composer install
  - composer update --prefer-lowest -n
  - composer update -n

script:
  - composer lint
